### ISSUE TITLE
How to identify "Unassigned" Cell?

### ISSUE THREAD

**Issue by ZixiangPAN** [ytomofuji/scLinaX#1]
Hi, I tried to apply scLinaX to my own data. I found two questions:

(1) After Annovar annotation, there are several SNPs that are located on several genes (downstream, intergenic or etc), how do you process with them(like select the most representative transcript like --pick in VEP or just drop them)?

(2) After running scLinaX, I found that in scLinaX_res$raw_exp_result, some cells may have both SNPs on Xa in "Allele A" and Xa in "Allele B", can I understand those cells are "unassigned" cells in your BioRxiv paper?

Thank you very much.

**Comment by ytomofuji** [comment]
Hi, Zixiang! Thank you for reaching out.

(1) Basically, we consider only variants that are on the transcripts. If variants overlap multiple transcripts, we remove such variants from our analysis in our bioRxiv manuscript.

(2) Yes! They will be not assigned which X chromosome is inactivated (we think some of them should be doublets). You can check the number of such cells in Supple Fig 3.

Thank you so much for your questions!
