### ISSUE TITLE
minor_allele_ratio : How to define the threshold for escapees?

### ISSUE THREAD

**Issue by ZixiangPAN** [ytomofuji/scLinaX#3]
Hi Dr Tomofuji,

I found that in the manucript you used the parameter minor_allele_ratio to identify escapees, and I noticed that you used the minor_allele_ratio>0.15 as the escapee threshold in Fig.4c. May I also ask that is 0.15 a fixed threshold for escapee identification or that is it variable between different datasets?

Additionally, could you please elaborate that why on Fig.4b PAR1 genes has higher mean/median Xi expression ratio than nonPAR escape genes?

Thank you very much.

Zixiang

**Comment by ytomofuji** [comment]
Dear Zixiang,

As you mentioned, a fixed threshold for escapee identification should be determined based on the features of the dataset and also on the aim of the analysis. Specifically, the background level of scLinaX estimates can be affected by dataset-specific features such as doublets ratio.

Genes on PAR1 region are expressed from both of the X chromosomes, so their ratio of the expression Xi should be high (ref: https://doi.org/10.1016/j.tig.2016.03.007).

Best,
Yoshi
