### ISSUE TITLE
add documentation on how to run cellsnp-lite and AnnoVar

### ISSUE THREAD

**Issue by massonix** [ytomofuji/scLinaX#4]
Hey @ytomofuji ! 

Great job with the package, it's exactly what we needed for our project.

Could I suggest to add a vignette on how to run cellsnp-lite + AnnoVar for one example dataset? It would really help users.

Many thanks!

**Comment by ytomofuji** [comment]
Hi @massonix!

Thank you for your comment.
I have just added the vignette for the pre-processing of the scLinaX input files.

In the future, I would like to create an easy-to-use wrapper to generate input files for scLinaX, but I haven't been able to dedicate enough time to this yet...

Thank you!

**Comment by massonix** [comment]
Thank you @ytomofuji !!

**Comment by massonix** [comment]
Is there any particular reason to use cellsnp-lite in mode 2 (without a given list of SNPs)? I had initially used in in mode 1

**Comment by ytomofuji** [comment]
Hi @massonix,

As I mentioned in the comment in the vignette, if you’ve already decided on a reference SNP panel, providing a list of SNPs would be a good option.
I’ll make sure to clarify this point in the next update!

Thank you!

**Comment by massonix** [comment]
Thanks ! I'm running it again with mode 2, I think i might be more reliable because of the increased number of SNPs profiled

**Comment by ytomofuji** [comment]
@massonix 
In mode 2, the number of SNPs is large, but many of them are likely false positives. By using a reference panel for QC, they will be filtered out and the resulting number of SNPs will be almost same as the mode 1.
One advantage of performing the analysis in mode 2 is that after obtaining ASE data, you gain flexibility in your QC pipeline, such as changing the reference panel if needed.

**Comment by massonix** [comment]
Very good points, I'll run it with both modes and compare the results. I did notice -as mentioned in the documentation- that mode 2 is very slow, and several jobs crashed.
