### ISSUE TITLE
should we consider the depth of the OTHER allele to calculate the depth of the REF allele?

### ISSUE THREAD

**Issue by massonix** [ytomofuji/scLinaX#5]
Hi @ytomofuji !

In the `scLinaX_preprocessing_example` vignette, the depth of the referece allele is calculated as:

```
RD<-DP-AD
```

However, I believe that DP is AD + RD + OTH. Therefore, shouldn't it be:

```
RD<-DP-AD - OTH
```

Many thanks in advance!

**Comment by ytomofuji** [comment]
Hi @massonix,

According to the README of cellsnp-lite, the cellSNP.tag.DP.mtx file is a SNP x cell sparse matrix in "Matrix Market exchange format," containing the sum of the allele depths for both the reference and alternative alleles (REF + ALT).
https://cellsnp-lite.readthedocs.io/en/latest/main/manual.html#output
Therefore, I believe RD should be calculated as DP - AD. I will review the script and data again to confirm.

Thank you!

**Comment by massonix** [comment]
Ah, you're right! Thanks for clarifying!
