### ISSUE TITLE
Which parameters shoud I adjust when data is sparser?

### ISSUE THREAD

**Issue by Elliott-1** [ytomofuji/scLinaX#6]
Dear Dr. Tomofuji,

First of all I'd like to say thank you so much for this package! It's been great to use and the vignette's provided have been very helpful. 

I had a question when running scLinaX on a sample with a lower cell count (around 8000 cells) and a lower average UMI (around 1000): Are there certain parameters in the run_scLinaX() and summarize_scLinaX() that would be best to lower/raise to maximize the amount of results I get without compromising too much statistical power?

For example, I noticed in your publication that you used a SNP_DETECTION_DP of 50 for the PBMC dataset, but 30 for the Multiome dataset. Perhaps reducing that even further? Are there any other suggested tweaks?  

Any feedback or guidance would be greatly appreciated!

Thanks,
Elliott

**Comment by ytomofuji** [comment]
Hi, Elliott. Thank you for your interest in scLinaX!

The per-cell UMI count is a particularly critical factor in estimating inactive X chromosomes. Although I have not examined this in detail, lowering the value of HE_allele_cell_number_THR may increase the number of cells that can be included in the analysis. However, depending on the data quality and other factors, there is a risk that the assignment of inactive X chromosomes may become less accurate. Therefore, it is difficult to definitively state which parameter setting is best.

Thank you!

**Comment by Elliott-1** [comment]
Hi Dr. Tomofuji,

Thank you! I'll try tuning the HE_allele_cell_number_THR.

On a related note, do you think it'd be okay to lower the QC_total_allele_THR to around 7-8? Also, what is the difference between QC_total_allele_THR in run_scLinaX() and summarize_scLinaX()? Should they always be the same value?

Best,
Elliott

**Comment by ytomofuji** [comment]
Hi Elliott,

In general, I think that the QC_total_allele_THR parameter should be the same for both run_scLinaX() and summarize_scLinaX(). The QC_total_allele_THR determines the minimum number of reads required for a site to be included in the analysis.

If you loosen the QC_total_allele_THR, the estimation of the minor allele expression ratio (used for estimating escape) may become noisier. This is an important point to consider. For example, observing 50% minor allele expression can mean either 1 out of 2 reads or 5 out of 10 reads, and the expected error margin differs significantly between these scenarios.

Thank you!

**Comment by Elliott-1** [comment]
Thank you! This was very helpful
